import { Product } from "@/types/Product";

export const dummyProducts: Product[] = [
  {
    id: 1,
    title: "Men's Active T-Shirt",
    price: 799,
    description: "High-quality breathable activewear for men.",
    category: "Men",
    image: "/products/tshirt-men.jpg",
    rating: 4,
  },
  {
    id: 2,
    title: "Women's Sports Bra",
    price: 999,
    description: "Comfort-fit stretchable sports bra.",
    category: "Women",
    image: "/products/sportsbra-women.jpg",
    rating: 4,
  },
  {
    id: 3,
    title: "Running Shorts",
    price: 599,
    description: "Quick-dry running shorts with side pocket.",
    category: "Men",
    image: "/products/shorts.jpg",
    rating: 4,
  },
  {
    id: 4,
    title: "Yoga Pants",
    price: 1199,
    description: "Stretchable & breathable yoga pants for women.",
    category: "Women",
    image: "/products/yogapants.jpg",
    rating: 4,
  },
  {
    id: 1,
    title: "Men's Active T-Shirt",
    price: 799,
    description: "High-quality breathable activewear for men.",
    category: "Men",
    image: "/products/tshirt-men.jpg",
    rating: 4,
  },
  {
    id: 2,
    title: "Women's Sports Bra",
    price: 999,
    description: "Comfort-fit stretchable sports bra.",
    category: "Women",
    image: "/products/sportsbra-women.jpg",
    rating: 4,
  },
  {
    id: 3,
    title: "Running Shorts",
    price: 599,
    description: "Quick-dry running shorts with side pocket.",
    category: "Men",
    image: "/products/shorts.jpg",
    rating: 4,
  },
  {
    id: 4,
    title: "Yoga Pants",
    price: 1199,
    description: "Stretchable & breathable yoga pants for women.",
    category: "Women",
    image: "/products/yogapants.jpg",
    rating: 4,
  },
];
